node {
    checkout scm 
}
pipeline {
    agent any
    environment {
        OS_PROJECT_DOMAIN_ID="default"
        OS_REGION_NAME="RegionOne"
        OS_USER_DOMAIN_NAME="Default"
        OS_PROJECT_NAME="demo"
        OS_IDENTITY_API_VERSION="3"
        OS_AUTH_URL="http://132.219.137.169/identity"
        OS_USERNAME="demo"
        OS_INTERFACE="public"
        OS_PASSWORD = credentials('OS_PASSWORD')
        CLOUDFLARE_EMAIL="simon.guilbault@calculquebec.ca"
        CLOUDFLARE_API_TOKEN = credentials('CLOUDFLARE_API_TOKEN')
        CLOUDFLARE_ZONE_API_TOKEN = credentials('CLOUDFLARE_API_TOKEN')
        CLOUDFLARE_DNS_API_TOKEN = credentials('CLOUDFLARE_API_TOKEN')
    }
    stages {
        stage('Setup') {
            steps {
                sh 'env'
                sh 'git clean -fdx'
                dir("tests/devstack/") {
                    sh 'bash setup.sh'
                }
            }
        }
        stage('Deploy') {
            steps {
                dir("tests/devstack/") {
                    timeout(time: 20, unit: 'MINUTES') {
                        sh 'bash deploy.sh'
                    }
                }
            }
        }
        stage('Test') {
            steps {
                dir("tests/devstack/") {
                    retry(3) {
                        sh 'bats test.bats'
                    }
                }
            }
        }
    }
    post {
        always {
            always {
                dir("tests/devstack/") {
                    sh 'bash destroy.sh'
                }
            }
        }
    }
}
